packages:
  - software
  - workflow
  - model
  - ui
  - block

catalog:
  "@platforma-sdk/model": ^1.45.0
  "@platforma-sdk/ui-vue": ^1.45.13
  "@platforma-sdk/workflow-tengo": ^5.6.2
  "@platforma-sdk/block-tools": ^2.6.21
  "@platforma-sdk/test": ^1.45.15
  "@platforma-sdk/tengo-builder": ^2.3.3
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0
  "@milaboratories/graph-maker": ^1.1.175
  "@milaboratories/helpers": ^1.12.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.7.5
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  "@vueuse/core": ^13.3.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1
  "sass-embedded": ^1.77.8

  "@changesets/cli": ^2.28.1
